### ISSUE TITLE
Questions about the datasets

### ISSUE THREAD

**Issue by TianjinTeda** [opendatalab/HA-DPO#2]
Hi,

Thanks for the excellent work!

I noticed that you have different training data (desc and pope) for different LVLM, could you provide the reasons of doing this? 
Do theses datasets have overlapping data?

**Comment by JulioZhao97** [comment]
Hi! Thanks for your interest in our work!

We used both descriptive (des) and question-answering (pope) data types for fine-tuning because the LLM is somewhat influenced by the format when answering different questions. Therefore, in order to make the model adapt to both descriptive tasks and question-answering tasks, we used both types of data. The stability of the model can be seen from the final SHR/POPE hallucination evaluation and general evaluations such as MME.

We used different data for different LVLMs, mainly considering that this is generated based on the current model's distribution, and the effect is somewhat better. In fact, when high-quality fine-tuning data generated by other models and GPT-4 is used for DPO fine-tuning, it can also improve the model's performance well. In other words, this data is relatively universal.
