### ISSUE TITLE
Question about the calculation on `gram-n repetition`

### ISSUE THREAD

**Issue by SDaoer** [opendatalab/HA-DPO#9]
```
def cal_repetition(sentence, n):
    sentence = sentence.replace(".", "").replace(":", "").replace("\n", "").replace("?", "").replace(",", "")
    allgrams = ngrams(sentence.split(), n)
    allgrams_list = []
    for gram in allgrams:
        allgrams_list.append(gram)
    return len(list(set(allgrams_list)))/len(allgrams_list)
```
The current implementation of the `cal_repetition` function appears to calculate the diversity of n-grams in a sentence, rather than the repetition rate. Specifically, the function returns the ratio of unique n-grams to the total number of n-grams. However, this does not directly measure n-gram repetition, as higher values indicate higher diversity (and lower repetition), while lower values indicate lower diversity (and higher repetition).

If there are any misunderstandings or inaccuracies in my interpretation, I would glad to discuss with you.

**Comment by JulioZhao97** [comment]
Thank you for pointing out the issue here. There may indeed be some problems with the method of calculating repetition. Although it can indirectly reflect the phenomenon of repetition in the model, it is unable to accurately quantify the degree of repetition. Could you please advise where I might find a reliable and popular method or code reference for measuring repetition? We will make corrections based on this in our subsequent work. Thank you very much!

**Comment by SDaoer** [comment]
What I mean is that the calculation method for the repetition rate might be exactly the opposite, because here, by using `set()` for deduplication, it calculates the unique n-gram ratio. I think directly converting it to `1 - len(list(set(allgrams_list)))/len(allgrams_list)` would reflect the repetition rate correctly.

**Comment by JulioZhao97** [comment]
> What I mean is that the calculation method for the repetition rate might be exactly the opposite, because here, by using `set()` for deduplication, it calculates the unique n-gram ratio. I think directly converting it to `1 - len(list(set(allgrams_list)))/len(allgrams_list)` would reflect the repetition rate correctly.

Oh, I see what you mean. So the misunderstanding is caused by the name of this function, in this ```cal_repitition``` function, we use ***a lower returned value indicates a larger repetition, and less model fluency (as in paper sec3.3 and Figure4)***, which can be counterintuitive. You can certainly converting it to ```1 - len(list(set(allgrams_list)))/len(allgrams_list)```, which can reflect the repetition rate more directly.
